config/routes.rb
Rails.application.routes.draw do
  resources :packages
  root 'couriers#index'
  
  resources :couriers
		
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/courier.rb
class Courier < ApplicationRecord
  has_many :packages, dependent: :destroy
  validates :name, presence: true, uniqueness: true
end

app/models/package.rb
class Package < ApplicationRecord
  belongs_to :courier

  validates :tracking_number, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/couriers_controller.rb
class CouriersController < ApplicationController
  before_action :set_courier, only: %i[show edit update destroy]

  # GET /couriers
  # GET /couriers.json
  def index
    @couriers = Courier.all
  end

  # GET /couriers/1
  # GET /couriers/1.json
  def show; end

  # GET /couriers/new
  def new
    @courier = Courier.new
  end

  # GET /couriers/1/edit
  def edit; end

  # POST /couriers
  # POST /couriers.json
  def create
    @courier = Courier.new(courier_params)

    respond_to do |format|
      if @courier.save
        format.html { redirect_to @courier, notice: 'Courier was successfully created.' }
        format.json { render :show, status: :created, location: @courier }
      else
        format.html { render :new }
        format.json { render json: @courier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /couriers/1
  # PATCH/PUT /couriers/1.json
  def update
    respond_to do |format|
      if @courier.update(courier_params)
        format.html { redirect_to @courier, notice: 'Courier was successfully updated.' }
        format.json { render :show, status: :ok, location: @courier }
      else
        format.html { render :edit }
        format.json { render json: @courier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /couriers/1
  # DELETE /couriers/1.json
  def destroy
    @courier.destroy
    respond_to do |format|
      format.html { redirect_to couriers_url, notice: 'Courier was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_courier
    @courier = Courier.find(params[:id])
  end

  def courier_params
    params.require(:courier).permit(:name, :email)
  end
end

app/controllers/packages_controller.rb
class PackagesController < ApplicationController
  before_action :set_package, only: %i[show edit update destroy]

  # GET /packages
  # GET /packages.json
  def index
    @q = Package.ransack(params[:q])
    @packages = @q.result(distinct: true)
  end

  # GET /packages/1
  # GET /packages/1.json
  def show; end

  # GET /packages/new
  def new
    @package = Package.new
  end

  # GET /packages/1/edit
  def edit; end

  # POST /packages
  # POST /packages.json
  def create
    @package = Package.new(package_params)

    respond_to do |format|
      if @package.save
        format.html { redirect_to @package, notice: 'Package was successfully created.' }
        format.json { render :show, status: :created, location: @package }
      else
        format.html { render :new }
        format.json { render json: @package.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /packages/1
  # PATCH/PUT /packages/1.json
  def update
    respond_to do |format|
      if @package.update(package_params)
        format.html { redirect_to @package, notice: 'Package was successfully updated.' }
        format.json { render :show, status: :ok, location: @package }
      else
        format.html { render :edit }
        format.json { render json: @package.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /packages/1
  # DELETE /packages/1.json
  def destroy
    @package.destroy
    respond_to do |format|
      format.html { redirect_to packages_url, notice: 'Package was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_package
    @package = Package.find(params[:id])
  end

  def package_params
    params.require(:package).permit(:tracking_number, :delivery_status, :courier_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/couriers_helper.rb
module CouriersHelper
end

app/helpers/packages_helper.rb
module PackagesHelper
end

app/views/couriers/_form.html.haml
= form_for @courier do |f|
  - if @courier.errors.any?
    #error_explanation
      %h2= "#{pluralize(@courier.errors.count, "error")} prohibited this courier from being saved:"
      %ul
        - @courier.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .actions
    = f.submit 'Save'

app/views/couriers/edit.html.haml
%h1 Editing courier

= render 'form'

= link_to 'Show', @courier
\|
= link_to 'Back', couriers_path

app/views/couriers/index.html.haml
%h1 Listing couriers

%table
  %thead
    %tr
      %th Name
      %th Email 
      %th 
  %tbody
    - @couriers.each do |courier|
      %tr
        %td= courier.name
        %td= courier.email
        %td
          = link_to courier do
            %i.fas.fa-eye
            Show
        %td
          = link_to edit_courier_path(courier) do
            %i.fas.fa-edit
            Edit
        %td
          = link_to courier, method: :delete, data: { confirm: 'Are you sure?' } do
            %i.fas.fa-trash
            Destroy
%br


= link_to new_courier_path do
  %i.fas.fa-user-plus
  Add new courier

app/views/couriers/new.html.haml
%h1 New courier

= render 'form'

= link_to 'Back', couriers_path

app/views/couriers/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @courier.name
%p
  %b Email:
  = @courier.email

= link_to edit_courier_path(@courier) do
  %i.fas.fa-edit
  Edit
\|
= link_to couriers_path do
  %i.fas.fa-arrow-left
  Back

= link_to new_package_path do
  %i.fas.fa-box-open
  Add new package

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DeliveryApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield